<?php
// $Id$

$SIDEBAR_DATA='
<p>The syntax highlighted source is automatically generated by PHP from
the plaintext script.</p>
<p>If you want to see the source of this page, have a look
<a href="/source.php?url=/source.php">here</a>.</p>
';

response_header('Show Source');

echo "<h2>Show Source</h2>\n";

if (empty($url)) {
    echo "<p>No page URL specified.</p>";
    response_footer();
    exit;
}
?>
<p>Source of: <?php echo $url; ?></p>

<?php

echo hdelim(); 

$legal_dirs = array(
    "/manual" => 1,
    "/include" => 1,
    "/stats" => 1);

$dir = dirname($url);
if (isset($legal_dirs[$dir])) {
    $page_name = $DOCUMENT_ROOT . $url;
} else {
    $page_name = basename($url);
}

echo("<!-- $page_name -->\n");

if (file_exists($page_name) && !is_dir($page_name)) {
    show_source($page_name);
} else if (@is_dir($page_name)) {
    echo "<p>No file specified.  Can't show source for a directory.</p>\n";
} else {
    echo "<p>Invalid URL specified.</p>\n";
}

response_footer();
?>  
