INSERT INTO users VALUES('ssb', '738aa8d3bc02eb8712acd0eb2cf6dfd5', 'Stig S. Bakken', 'stig@php.net', 'http://www.pvv.org/~ssb/', '2001-04-18', 'ssb', NULL, 1, 1, 1, NULL);
INSERT INTO maintains VALUES('ssb','HTTP','lead');

-- INSERT INTO packages (name,placeholder) VALUES('',1);
INSERT INTO packages (name,summary,copyright) VALUES('DB','PEAR database abstraction layer','PHP License');
INSERT INTO packages (name,parent) VALUES('Benchmark',NULL);
INSERT INTO packages (name,parent) VALUES('CMD',NULL);
INSERT INTO packages (name,parent) VALUES('Cache',NULL);
INSERT INTO packages (name,parent,placeholder) VALUES('Console',NULL,1);
INSERT INTO packages (name,parent) VALUES('Console_Getopt','Console');
INSERT INTO packages (name,parent) VALUES('Crypt',NULL);
INSERT INTO packages (name,parent) VALUES('Date',NULL);
INSERT INTO packages (name,parent,placeholder) VALUES('File',NULL,1);
INSERT INTO packages (name,parent) VALUES('File_Find','File');
INSERT INTO packages (name,parent) VALUES('File_SearchReplace','File');
INSERT INTO packages (name,parent) VALUES('File_Passwd','File');
INSERT INTO packages (name,parent,placeholder) VALUES('HTML',NULL,1);
INSERT INTO packages (name,parent) VALUES('HTML_IT[X]','HTML');
INSERT INTO packages (name,parent) VALUES('HTML_Form','HTML');
INSERT INTO packages (name,parent) VALUES('HTML_Menu','HTML');
INSERT INTO packages (name,parent) VALUES('HTML_Processor','HTML');
INSERT INTO packages (name,parent,summary) VALUES('HTTP',NULL,'Some HTTP-related functions');
INSERT INTO packages (name,parent) VALUES('HTTP_Compress','HTTP');
INSERT INTO packages (name,parent,placeholder) VALUES('Image',NULL,1);
INSERT INTO packages (name,parent) VALUES('Image_Remote','Image');
INSERT INTO packages (name,parent) VALUES('Log',NULL);
INSERT INTO packages (name,parent) VALUES('Mail',NULL);
INSERT INTO packages (name,parent) VALUES('Math',NULL);
INSERT INTO packages (name,parent,placeholder) VALUES('Net',NULL,1);
INSERT INTO packages (name,parent) VALUES('Net_Curl','Net');
INSERT INTO packages (name,parent) VALUES('Net_SMTP','Net');
INSERT INTO packages (name,parent) VALUES('Net_Socket','Net');
INSERT INTO packages (name,parent) VALUES('Numbers',NULL);
INSERT INTO packages (name,parent) VALUES('PEAR',NULL);
INSERT INTO packages (name,parent) VALUES('PHPDoc',NULL);
INSERT INTO packages (name,parent) VALUES('Payment',NULL);
INSERT INTO packages (name,parent,placeholder) VALUES('Science',NULL,1);
INSERT INTO packages (name,parent) VALUES('Science_Chemistry','Science');
INSERT INTO packages (name,parent) VALUES('Shedule',NULL);
INSERT INTO packages (name,parent,placeholder) VALUES('XML',NULL,1);
INSERT INTO packages (name,parent) VALUES('XML_RPC','XML');
INSERT INTO packages (name,parent) VALUES('XML_Parser','XML');
INSERT INTO packages (name,parent) VALUES('XML_Render','XML');

-- INSERT INTO releases VALUES(NULL, 'HTTP', '1.0', 'ssb', '2001-04-18', 'Initial release');
