INSERT INTO users VALUES('SSB', '8c38dfa80e2bf8b2076a30848f111300', 'Stig Bakken', 'ssb@fast.no', 'http://www.pvv.org/~ssb/', 944079834, 944079834, 'SSB', 1, 1, 1, NULL);
INSERT INTO maintains VALUES('SSB','DB','lead');

-- INSERT INTO packages (name,placeholder) VALUES('',1);
INSERT INTO packages (name,summary,copyright) VALUES('DB','PEAR database abstraction layer','PHP License');
INSERT INTO packages (name) VALUES('Benchmark');
INSERT INTO packages (name) VALUES('CMD');
INSERT INTO packages (name) VALUES('Cache');
INSERT INTO packages (name,placeholder) VALUES('Console',1);
INSERT INTO packages (name) VALUES('Console_Getopt');
INSERT INTO packages (name) VALUES('Crypt');
INSERT INTO packages (name) VALUES('Date');
INSERT INTO packages (name,placeholder) VALUES('File',1);
INSERT INTO packages (name) VALUES('File_Find');
INSERT INTO packages (name) VALUES('File_SearchReplace');
INSERT INTO packages (name) VALUES('File_Passwd');
INSERT INTO packages (name,placeholder) VALUES('HTML',1);
INSERT INTO packages (name) VALUES('HTML_IT[X]');
INSERT INTO packages (name) VALUES('HTML_Form');
INSERT INTO packages (name) VALUES('HTML_Menu');
INSERT INTO packages (name) VALUES('HTML_Processor');
INSERT INTO packages (name) VALUES('HTTP');
INSERT INTO packages (name) VALUES('HTTP_Compress');
INSERT INTO packages (name,placeholder) VALUES('Image',1);
INSERT INTO packages (name) VALUES('Image_Remote');
INSERT INTO packages (name) VALUES('Log');
INSERT INTO packages (name) VALUES('Mail');
INSERT INTO packages (name) VALUES('Math');
INSERT INTO packages (name,placeholder) VALUES('Net',1);
INSERT INTO packages (name) VALUES('Net_Curl');
INSERT INTO packages (name) VALUES('Net_SMTP');
INSERT INTO packages (name) VALUES('Net_Socket');
INSERT INTO packages (name) VALUES('Numbers');
INSERT INTO packages (name) VALUES('PEAR');
INSERT INTO packages (name) VALUES('PHPDoc');
INSERT INTO packages (name) VALUES('Payment');
INSERT INTO packages (name,placeholder) VALUES('Science',1);
INSERT INTO packages (name) VALUES('Science_Chemistry');
INSERT INTO packages (name) VALUES('Shedule');
INSERT INTO packages (name,placeholder) VALUES('XML',1);
INSERT INTO packages (name) VALUES('XML_RPC');
INSERT INTO packages (name) VALUES('XML_Parser');
INSERT INTO packages (name) VALUES('XML_Render');
