INSERT INTO users VALUES('SSB', '8c38dfa80e2bf8b2076a30848f111300', 'Stig Bakken', 'ssb@fast.no', 'http://www.pvv.org/~ssb/', 944079834, 944079834, 'SSB', 1, 1, 1, NULL);
INSERT INTO maintains VALUES('SSB','DB','lead');

INSERT INTO domains (name,parent) VALUES('Benchmark',NULL);
INSERT INTO domains (name,parent) VALUES('CMD',NULL);
INSERT INTO domains (name,parent) VALUES('Cache',NULL);
INSERT INTO domains (name,parent) VALUES('Console',NULL);
INSERT INTO domains (name,parent) VALUES('Crypt',NULL);
INSERT INTO domains (name,parent) VALUES('DB',NULL);
INSERT INTO domains (name,parent) VALUES('Date',NULL);
INSERT INTO domains (name,parent) VALUES('File',NULL);
INSERT INTO domains (name,parent) VALUES('HTML',NULL);
INSERT INTO domains (name,parent) VALUES('HTTP',NULL);
INSERT INTO domains (name,parent) VALUES('Image',NULL);
INSERT INTO domains (name,parent) VALUES('Log',NULL);
INSERT INTO domains (name,parent) VALUES('Mail',NULL);
INSERT INTO domains (name,parent) VALUES('Math',NULL);
INSERT INTO domains (name,parent) VALUES('Net',NULL);
INSERT INTO domains (name,parent) VALUES('Numbers',NULL);
INSERT INTO domains (name,parent) VALUES('PEAR',NULL);
INSERT INTO domains (name,parent) VALUES('PHPDoc',NULL);
INSERT INTO domains (name,parent) VALUES('Payment',NULL);
INSERT INTO domains (name,parent) VALUES('Schedule',NULL);
INSERT INTO domains (name,parent) VALUES('XML',NULL);

INSERT INTO packages (name,summary,copyright) VALUES('DB','PEAR database abstraction layer','PHP License');
INSERT INTO packages (name) VALUES('Benchmark');
INSERT INTO packages (name) VALUES('CMD');
INSERT INTO packages (name) VALUES('Cache');
INSERT INTO packages (name) VALUES('Console_Getopt');
INSERT INTO packages (name) VALUES('Crypt');
INSERT INTO packages (name) VALUES('Date');
INSERT INTO packages (name,domain) VALUES('File_Find','File');
INSERT INTO packages (name,domain) VALUES('File_SearchReplace','File');
INSERT INTO packages (name,domain) VALUES('File_Passwd','File');
INSERT INTO packages (name,domain) VALUES('HTML_IT[X]','HTML');
INSERT INTO packages (name,domain) VALUES('HTML_Form','HTML');
INSERT INTO packages (name,domain) VALUES('HTML_Menu','HTML');
INSERT INTO packages (name,domain) VALUES('HTML_Processor','HTML');
INSERT INTO packages (name) VALUES('HTTP');
INSERT INTO packages (name,domain) VALUES('HTTP_Compress','HTTP');
INSERT INTO packages (name,domain) VALUES('Image_Remote','Image');
INSERT INTO packages (name) VALUES('Log');
INSERT INTO packages (name) VALUES('Mail');
INSERT INTO packages (name) VALUES('Math');
INSERT INTO packages (name,domain) VALUES('Net_Curl','Net');
INSERT INTO packages (name,domain) VALUES('Net_SMTP','Net');
INSERT INTO packages (name,domain) VALUES('Net_Socket','Net');
INSERT INTO packages (name) VALUES('Numbers');
INSERT INTO packages (name) VALUES('PEAR');
INSERT INTO packages (name) VALUES('PHPDoc');
INSERT INTO packages (name) VALUES('Payment');
INSERT INTO packages (name) VALUES('Shedule');
INSERT INTO packages (name,domain) VALUES('XML_RPC','XML');
INSERT INTO packages (name,domain) VALUES('XML_Parser','XML');
INSERT INTO packages (name,domain) VALUES('XML_Render','XML');
